name: Application Code

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup .NET Core
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 3.1.301

      - name: Build WPF App
        working-directory: src/CRUDApp
        run: dotnet build --configuration Release

      # - name: Tests with dotnet
      #   run: dotnet test ./src/WP.WebAPI.Tests/WP.WebAPI.Tests.csproj
